"""
Django setting for Whiteboard project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-o^av5(zx!5zc(-*@70p+qixd_k=@cq!y@3=dt+w-ki!(j=w^fp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'WhiteboardApp.apps.WhiteboardappConfig',
    'djongo',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Whiteboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Whiteboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'WhiteboardDB',
#         'CLIENT': {
#             'host': 'localhost',
#             'port': 27017,
#             'username': '',
#             'password': '',
#             'authMechanism': 'SCRAM-SHA-1',
#             'authSource': 'admin',
#         },
#     },
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Absolute filesystem path to
MEDIA_URL = '/media/'  # The URL prefix for media files

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
LOGIN_URL = 'WhiteboardApp:login_post'
LOGIN_REDIRECT_URL = 'WhiteboardApp:main_banner'

# Stripe settings
STRIPE_PUBLIC_KEY = 'pk_test_51NS9eOHitL9rNw3gWw65ZPSFcvUg9tnkcjb0M3W7t24Vgm9xLALSy2p4zbxcrkDY1AMQgf9nQoXVWqKmwGPOexFX00dKE3R2ay'
STRIPE_SECRET_KEY = 'sk_test_51NS9eOHitL9rNw3g7XnjlVvsA6msTP0SaRBS89RPl7BKBGPHrjsE7W2R1aXM1oEkwY2QyOPVYBn6H6LZTG5nHoBj00OYaT28EI'

# Twilio settings
TWILIO_ACCOUNT_SID = 'ACb3b88c505441e68232a84742fc55a34c'
TWILIO_AUTH_TOKEN = '54d06764fff943dd4bfb4b7b0944f3bf'
TWILIO_FROM_NUMBER = '+16206791334'
TWILIO_TO_NUMBER = '+12267243681'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'whiteboard.internetapplication@gmail.com'
EMAIL_HOST_PASSWORD = 'sarezeosvfwvsxpe'
