# Generated by Django 4.1.9 on 2023-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="name",
            field=models.CharField(
                choices=[
                    ("no", "No-Membership"),
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("bronze", "Bronze"),
                ],
                default="no",
                max_length=100,
            ),
        ),
    ]
