# Generated by Django 4.1.9 on 2023-07-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0003_alter_membership_name_alter_student_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="membership",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="WhiteboardApp.membership",
            ),
        ),
    ]
