# Generated by Django 4.1.9 on 2023-07-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0004_alter_student_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="expertise",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
