# Generated by Django 4.1.9 on 2023-07-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0007_remove_instructor_biography_alter_instructor_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollars"),
                    ("CAD", "Canadian Dollars"),
                    ("EUR", "Euros"),
                    ("GBP", "British Pounds"),
                    ("JPY", "Japanese Yen"),
                    ("CHF", "Swiss Francs"),
                    ("AUD", "Australian Dollars"),
                    ("NZD", "New Zealand Dollars"),
                    ("BRL", "Iranian Rial"),
                    ("CNY", "Chinese Yuan"),
                ],
                max_length=3,
            ),
        ),
    ]
