# Generated by Django 4.1.9 on 2023-07-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0008_alter_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="cvc",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="expiration_date",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
