# Generated by Django 4.1.9 on 2023-07-15 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0009_payment_card_number_payment_cvc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF File"),
                            ("Voice", "Voice File"),
                            ("Video", "Video File"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="contents/"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WhiteboardApp.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentContentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WhiteboardApp.content",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WhiteboardApp.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "student_content_progress",
                "db_table": "WhiteboardApp_student_content_progress",
            },
        )
    ]
