# Generated by Django 4.1.9 on 2023-07-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0010_content_studentcontentprogress_delete_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcontentprogress",
            name="progress",
        )
    ]
