# Generated by Django 4.1.9 on 2023-07-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0011_remove_studentcontentprogress_progress_and_more"),
    ]
