# Generated by Django 4.1.9 on 2023-07-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0012_delete_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="progress",
        )
    ]
