# Generated by Django 4.1.9 on 2023-07-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhiteboardApp", "0014_rename_studentcontentprogress_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
