# Generated by Django 4.1.10 on 2023-07-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteboardApp', '0016_student_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='verification_code',
        ),
    ]
